name: Discord Bot Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust the version as per your requirement

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: bash ./.github/workflows/deploy.sh
